<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>7.3</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <NuGetAudit>false</NuGetAudit>
    <NoWarn>$(NoWarn);NU1900</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logger.NLog\Logger.NLog.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.0.3" />
  </ItemGroup>
</Project>
